let firstName='awa', LastName='kiyang', Country='cameroon', City='yaounde', Age=22, isMarried='yes', Year=2024
console.log(typeof firstName)
console.log(typeof LastName)
console.log(typeof Country)
console.log(typeof City)
console.log(typeof Age)
console.log(typeof isMarried)
console.log(typeof Year)
console.log(typeof '10' == typeof 10)
console.log(parseInt('9.8') == 10)
console.log(Math.ceil(parseFloat('9.8')) == 10)  
console.log('waar'.length == 'papa'.length)
console.log(4 == '4')
console.log('python'.length != 'jargon'.length)
console.log(!('python'.includes('on') && 'jargon'.includes('on')))
