let challenge = '30 Days of javascript'
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substring(0,2))
console.log(challenge.substring(3,21))
console.log(challenge.includes('script'))
console.log(challenge.split(' '))
console.log(challenge.split())
//
console.log(challenge.replace('javascript','Python'))
console.log(challenge[15])
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt(challenge.indexOf('j')))
console.log(challenge.indexOf('j'))
console.log(challenge.charCodeAt(11))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
console.log(challenge.search('a'))
console.log(challenge.trim())
console.log(challenge.startsWith('30'))
console.log(challenge.endsWith('script'))
console.log(challenge.match(/a/g))
console.log(challenge.repeat(2))

//exercise 2
console.log('the qoute \'There is no exercise better for the heart than reaching down and lift people up.\' by john holmes')
console.log('\"asear combi\"')
console.log(typeof '10' == typeof 10)
console.log(typeof parseInt('10') == typeof 10)
console.log(typeof 9.8 == typeof 10)
console.log(parseFloat(9.8) == 10)
console.log(Math.ceil(9.8) == 10)
console.log(('python' && 'jargon'.includes('on')))
console.log(('i hope this course is not full of jargon').includes('jargon'))
console.log(Math.floor(Math.random() * 101))
console.log(('Javascript').charAt(Math.floor(Math.random() * 10)))
console.log('1 1 1 1 1\n2 1 2 4 8\n3 1 3 9 27\n4 1 3 9 27\n5 1 5 25 125')

//execise level 3
